services:
  humbug:
    build: .
    ports:
      - 8889:8888
      - 4200:4200
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./:/workspace/humbug
      - ./models:/models/
      - ./data:/data/
